# Generated by Django 3.1.4 on 2024-02-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20240204_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='current_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
