# Generated by Django 3.1.4 on 2024-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(default='Salary', max_length=100),
        ),
    ]
